export const endpoints = {
    rootEndpoint: 'localhost:44345/api',
    productEndpoints: {
        get: 'Product/GetAll',
        getProductDetailsDto: 'Product/GetDetailsAsync',
        getProductListDto: 'Product/GetListAsync',
        add: 'Product/Add',
        update: 'Product/Update',
        delete: 'Product/Delete',
    },
    categoryEndpoints: {
        getAll: 'Category/GetAll',
        get: 'Category/Get',
        getCategoryListDto: 'Category/GetList',
        getCategoryListDtoAsync: 'Category/GetListAsync',
        getCategoryDetailsDto: 'Category/GetDetails',
        getCategoryDetailsDtoAsync: 'Category/GetDetailsAsync',
        add: 'Category/Add',
        update: 'Category/Update',
        delete: 'Category/Delete',
    },
    bomEndpoints: {
        getAll: 'Bom/GetAll',
        get: 'Bom/Get',
        getDetailsDto: 'Bom/GetDetails',
        getDetailsDtoAsync: 'Bom/GetDetailsAsync',
        getListDto: 'Bom/GetExtendedList',
        getListDtoAsync: 'Bom/GetExtendedListAsync',
        componentGet: 'Bom/Components/Get',
        componentGetAsync: 'Bom/Components/GetAsync',
        componentList: 'Bom/Components/GetList',
        componentListAsync: 'Bom/Components/GetListAsync',
        componentAdd: 'Bom/Components/Add',
        componentRemove: 'Bom/Components/Delete',
    },
    warehouseEndpoints: {
        getAll: 'Warehouse/GetAll',
        get: 'Warehouse/Get',
        add: 'Warehouse/Add',
        update: 'Warehouse/Update',
        delete: 'Warehouse/Delete',
    },
    scrapEndpoints: {
        get: 'Scrap/Get',
        getProductDetailsDto: 'Scrap/GetDetails',
        getList: 'Scrap/GetList',
        getProductListDto: 'Scrap/GetExtendedList',
        add: 'Scrap/Add',
        update: 'Scrap/Update',
        delete: 'Scrap/Delete',
    },
    locationEndpoints: {

    },
}